[build]
  command = "dotnet run --project ./src/Bookland/"
  publish = "./output"

[build.environment]
  TZ = "Pacific/Auckland"

[[redirects]]
from = "/blog/the-index-card"
to = "/blog/index-card"
status = 301
force = false

[[redirects]]
from = "/blog/the-art-of-learning"
to = "/blog/art-of-learning"
status = 301
force = false

[[redirects]]
from = "/blog/the-motive"
to = "/blog/motive"
status = 301
force = false
