name: 'Live'

trigger:
    batch: false
    branches:
        include:
            - master
    paths:
        exclude:
            - content/*
            - ci/*
            - scripts/*

pr: none

variables:
    - template: azure-pipelines.vars.yml

jobs:
    - template: azure-pipelines.common.yml
      parameters:
          deployScriptParams: '--prod'
          netlifySiteId: $(netlify.siteId)
          netlifyToken: $(netlify.token)
          message: 'Release'
