SiteTitle: 'Discoveries in Bookland'
SiteDescription: 'A blog for book reviews'
SiteUrl: 'https://www.discoveriesinbookland.com'
TwitterUsername: 'ankur_sheel'
ReadingTimeWordsPerMinute: 238
#
#
#twitterUsername: 'ankur_sheel',
#googleTagManagerId: 'GTM-MQGJF8W',
#icon: 'content/images/inaki-del-olmo-bookshelf.jpg',
#headerTitle: 'Home',
#headerLinksIcon: 'inaki-del-olmo-bookshelf.jpg',
#webMonetization: '$ilp.uphold.com/FpRgJHkQhkhb',
#donateText: 'Did you learn something or find this summary interesting?',
#buyMeACoffee: {
#  link: 'https://www.buymeacoffee.com/ankursheel',
#  altText: 'Show your support',
#},
#socialLinks: {
#  twitter: {
#    url: 'https://twitter.com/ankur_sheel',
#    text: 'Follow me on Twitter',
#  },
#  github: {
#    url: '',
#    text: '',
#  },
#  linkedin: {
#    url: '',
#    text: '',
#  },
#  rss: {
#    url: '/blog/rss.xml',
#    text: 'Subsribe on RSS',
#  },
#},
#headerLinks: [
#  {
#    label: 'Blog',
#    url: '/blog',
#  },
#
#  {
#    label: 'Tags',
#    url: '/tags',
#  },
#  {
#    label: 'Contact Me',
#    url: '/contact',
#  },
#],
#footerLinks: [
#  {
#    sectionName: 'Follow me',
#    links: [
#      {
#        label: 'Twitter',
#        url: 'https://twitter.com/ankur_sheel',
#      },
#    ],
#  },
#],
#};
