Title: 'Discoveries in Bookland'
Description: 'A blog for book reviews'
Host: 'www.discoveriesinbookland.com'
LinksUseHttps: true
TwitterUsername: 'ankur_sheel'
BuyMeACoffeeUsername: 'ankursheel'
ReadingTimeWordsPerMinute: 238
NumberOfRelatedPosts: 4
HeaderLinks:
  - Title: About
    Url: /about
  - Title: All Summaries
    Url: /blog
  - Title: All Tags
    Url: /tags
  - Title: Contact
    Url: /contact
#GoogleTagManagerId: GTM-MQGJF8W
GoatCounterCode: discoveriesinbookland
#
#
#icon: 'content/images/inaki-del-olmo-bookshelf.jpg',
#headerTitle: 'Home',
#headerLinksIcon: 'inaki-del-olmo-bookshelf.jpg',
#webMonetization: '$ilp.uphold.com/FpRgJHkQhkhb',
#donateText: 'Did you learn something or find this summary interesting?',
#buyMeACoffee: {
#  link: 'https://www.buymeacoffee.com/ankursheel',
